import {MigrationInterface, QueryRunner} from "typeorm";
import { PostgresConnectionOptions } from "typeorm/driver/postgres/PostgresConnectionOptions";

export class initdb1610441756645 implements MigrationInterface {
    name = 'initdb1610441756645'

    public async up(queryRunner: QueryRunner): Promise<void> {
        const {schema} = queryRunner.connection.options as PostgresConnectionOptions;
        await queryRunner.query(`CREATE TABLE "${schema}"."adm-expense" ("id" character varying NOT NULL, "description" character varying NOT NULL, "paidDate" character varying NOT NULL, "value" character varying NOT NULL, "currency" character varying NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "period" character varying NOT NULL, CONSTRAINT "UQ_4d85279c7bc3ab10325fb20c368" UNIQUE ("description"), CONSTRAINT "PK_0e7270689ba0ae3f7305cf19dc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."da-expense" ("id" character varying NOT NULL, "description" character varying NOT NULL, "paidDate" character varying NOT NULL, "value" character varying NOT NULL, "currency" character varying NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "period" character varying NOT NULL, CONSTRAINT "UQ_4f21397b8bb77f6b12d6b64488f" UNIQUE ("description"), CONSTRAINT "PK_8e4879ed66b78c558b7bcd7d861" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."selling-expense" ("id" character varying NOT NULL, "description" character varying NOT NULL, "paidDate" character varying NOT NULL, "value" character varying NOT NULL, "currency" character varying NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "period" character varying NOT NULL, CONSTRAINT "UQ_2a3c91e6dfd303c29e6f2ce3e45" UNIQUE ("description"), CONSTRAINT "PK_3be002babd7884c87cae376350d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."tax-expense" ("id" character varying NOT NULL, "description" character varying NOT NULL, "paidDate" character varying NOT NULL, "value" character varying NOT NULL, "currency" character varying NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "period" character varying NOT NULL, CONSTRAINT "UQ_75af5b114dcbd002de689efd6a3" UNIQUE ("description"), CONSTRAINT "PK_ee76069f1284ce14457b6be14bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."activity-area" ("id" character varying NOT NULL, "name" character varying NOT NULL, "activity" character varying NOT NULL, "warehouseId" character varying, CONSTRAINT "PK_02c495451d92f0d88bf6ff404da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."warehouse" ("id" character varying NOT NULL, "name" character varying NOT NULL, "location" character varying NOT NULL, CONSTRAINT "PK_4d177f2e6bda90342dd7279070e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."storage-section" ("id" character varying NOT NULL, "name" character varying NOT NULL, "storageTypeId" character varying, CONSTRAINT "PK_4e894fe4036e54160d1b6720843" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."storage-type" ("id" character varying NOT NULL, "name" character varying NOT NULL, "areaType" character varying NOT NULL, "warehouseId" character varying, CONSTRAINT "PK_5883aa54609fe754cf1734bcfab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."storage-bin" ("id" character varying NOT NULL, "name" character varying NOT NULL, "maxWeight" integer NOT NULL, "totalCapicity" integer NOT NULL, "type" character varying NOT NULL, "storageTypeId" character varying, "storageSectionId" character varying, "activityAreaId" character varying, CONSTRAINT "PK_41891687e04f6e51c09624a5fc6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."packging-material" ("id" character varying NOT NULL, "type" character varying NOT NULL, "category" character varying NOT NULL, "tareWeight" integer, "tareVolume" integer, "capacities" integer, CONSTRAINT "PK_3ce744b4f9c56e2b6e0ffa6dab3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."package-specification" ("id" character varying NOT NULL, "name" character varying NOT NULL, "packingLevel" integer NOT NULL, "quantity" integer NOT NULL, "productId" character varying, "packgingMaterialId" character varying, CONSTRAINT "PK_93e39e5f992d5bf754e4df73360" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."product" ("id" character varying NOT NULL, "name" character varying NOT NULL, "weight" integer, "volume" integer, "category" character varying, "unitOfMeasurement" character varying NOT NULL, "color" character varying, CONSTRAINT "PK_30273c9826ff30ea0872d756194" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."handling-unit" ("id" character varying NOT NULL, "parentId" character varying, "type" character varying NOT NULL, "dimension" integer NOT NULL, "weight" integer NOT NULL, "volume" integer NOT NULL, "totalPrice" integer NOT NULL, "currency" character varying NOT NULL, "quantity" integer NOT NULL, "status" character varying NOT NULL, "productId" character varying, "packageSpecificationId" character varying, "packgingMaterialId" character varying, CONSTRAINT "PK_f111a02c36cfc5a0242c2cb41a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."sourcing-shipment" ("id" character varying NOT NULL, "receivedDate" character varying NOT NULL, "status" character varying NOT NULL, "fee_value" integer NOT NULL, "currency" character varying NOT NULL, "sourcingOrderId" character varying, CONSTRAINT "REL_514276e6521690fd002e195324" UNIQUE ("sourcingOrderId"), CONSTRAINT "PK_68d238d1b36842c8b91fbb1ed82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."account-payable" ("id" character varying NOT NULL, "dueDate" character varying NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "currency" character varying NOT NULL, "value" integer NOT NULL, "period" character varying NOT NULL, "sourcingPaymentId" character varying, CONSTRAINT "REL_22b94f1172a13fda9171f373dc" UNIQUE ("sourcingPaymentId"), CONSTRAINT "PK_d9c4f09b48cb4b9ceff8d6fbe57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."account" ("id" character varying NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "currency" character varying NOT NULL, "value" integer NOT NULL, "type" character varying NOT NULL, "period" character varying NOT NULL, "paymentVoucherId" character varying, CONSTRAINT "PK_a10032ebab7369a80a2af73a6ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."payment-voucher" ("id" character varying NOT NULL, "createDate" character varying NOT NULL, "skuId" character varying NOT NULL, "productId" character varying NOT NULL, "sourcingPaymentId" character varying, CONSTRAINT "PK_a4424415b2b12dc21aac2c741dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."sourcing-payment" ("id" character varying NOT NULL, "status" character varying NOT NULL, "value" integer NOT NULL, "currency" character varying NOT NULL, "sourcingOrderId" character varying, CONSTRAINT "PK_8611ad9119a4ec21a6115f44180" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."sourcing-order" ("id" character varying NOT NULL, "createdDate" character varying NOT NULL, "addingServiceId" character varying, "sourcingBusinessContractId" character varying, CONSTRAINT "PK_a0beb1d385e9553384797a1a08d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."product-sourcing-order" ("id" character varying NOT NULL, "quantity" integer NOT NULL, "totalPricr" integer NOT NULL, "discount" integer NOT NULL, "currency" character varying NOT NULL, "skuId" character varying, "sourcingOrderId" character varying, CONSTRAINT "PK_64da3f209845b612118441e4ccc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."product-selling-contract" ("id" character varying NOT NULL, "quantity" integer NOT NULL, "totalPricr" integer NOT NULL, "discount" integer NOT NULL, "currency" character varying NOT NULL, "skuId" character varying, "sellingBusinessContractId" character varying, CONSTRAINT "PK_2b6448ad962a1822bbcf989e3f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."commission" ("id" character varying NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "currency" character varying NOT NULL, "value" integer NOT NULL, "period" character varying NOT NULL, "sellingBusinessContractId" character varying, CONSTRAINT "REL_c452e76c3467cfb6c23fbe5d9f" UNIQUE ("sellingBusinessContractId"), CONSTRAINT "PK_6562270685bed408b7e3c9036fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."selling-business-contract" ("id" character varying NOT NULL, "createdDate" character varying NOT NULL, "moneyValue" integer NOT NULL, "businessPartnerId" character varying, CONSTRAINT "PK_a55bb6c38f609fbc286e1cd1310" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."selling-shipment" ("id" character varying NOT NULL, "receivedDate" character varying NOT NULL, "status" character varying NOT NULL, "fee_value" integer NOT NULL, "currency" character varying NOT NULL, "sellingOrderId" character varying, CONSTRAINT "REL_3ac515f6c9b4db426141ae7206" UNIQUE ("sellingOrderId"), CONSTRAINT "PK_19c2b6b300a64e917e01e79568a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."account-receivable" ("id" character varying NOT NULL, "dueDate" character varying NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "currency" character varying NOT NULL, "value" integer NOT NULL, "period" character varying NOT NULL, "sellingPaymentId" character varying, CONSTRAINT "REL_e1f74a17ff57f3694a610b8a05" UNIQUE ("sellingPaymentId"), CONSTRAINT "PK_0ffd1a08f821d40783b805073ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."revenue" ("id" character varying NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "currency" character varying NOT NULL, "value" integer NOT NULL, "type" character varying NOT NULL, "period" character varying NOT NULL, "receiptId" character varying, CONSTRAINT "PK_448284a5db7d4f34e8fe668e655" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."receipt" ("id" character varying NOT NULL, "createDate" character varying NOT NULL, "skuId" character varying NOT NULL, "productId" character varying NOT NULL, "sellingPaymentId" character varying, CONSTRAINT "PK_597db596dcd61479192981e2778" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."selling-payment" ("id" character varying NOT NULL, "status" character varying NOT NULL, "value" integer NOT NULL, "currency" character varying NOT NULL, "sellingOrderId" character varying, CONSTRAINT "PK_c47c073d6b7c854dafa8d886cba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."selling-order" ("id" character varying NOT NULL, "createdDate" character varying NOT NULL, "value" integer, "addingServiceType" character varying, "sellingBusinessContractId" character varying, CONSTRAINT "PK_6ea0734f572796f37719dde5cb3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."product-selling-order" ("id" character varying NOT NULL, "quantity" integer NOT NULL, "totalPricr" integer NOT NULL, "discount" integer NOT NULL, "currency" character varying NOT NULL, "skuId" character varying, "sellingOrderId" character varying, CONSTRAINT "PK_3b6f115d13927d14b792d6decd2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."sku" ("id" character varying NOT NULL, "productName" character varying NOT NULL, "productId" character varying NOT NULL, "expireDate" character varying NOT NULL, "unitPrice" integer NOT NULL, "currency" character varying NOT NULL, "quantity" integer NOT NULL, "storageBinId" character varying, "handlingUnitId" character varying, CONSTRAINT "PK_643c5e9e6e68024c5ffef2f6538" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."product-sourcing-contract" ("id" character varying NOT NULL, "quantity" integer NOT NULL, "totalPricr" integer NOT NULL, "discount" integer NOT NULL, "currency" character varying NOT NULL, "skuId" character varying, "sourcingBusinessContractId" character varying, CONSTRAINT "PK_b2416486e1050582438cc7a5e96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."sourcing-business-contract" ("id" character varying NOT NULL, "createdDate" character varying NOT NULL, "moneyValue" integer NOT NULL, "businessPartnerId" character varying, CONSTRAINT "PK_5c3d7540b3b1f69a3fb08597df0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "${schema}"."business-partner" ("id" character varying NOT NULL, "fullName" character varying NOT NULL, "address" character varying, "taxInfo" character varying, "phone" character varying, "email" character varying, "discount" integer, "category" character varying, "function" character varying, "status" character varying NOT NULL, CONSTRAINT "UQ_02b2b4d5166845df39a8415f0ba" UNIQUE ("fullName"), CONSTRAINT "PK_ee50d95d8972ab3c4a66857bca1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "${schema}"."activity-area" ADD CONSTRAINT "FK_d8d7d51e82a7eb6b08f5d110e23" FOREIGN KEY ("warehouseId") REFERENCES "${schema}"."warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."storage-section" ADD CONSTRAINT "FK_398a26bd1bdcc7b90304232cfac" FOREIGN KEY ("storageTypeId") REFERENCES "${schema}"."storage-type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."storage-type" ADD CONSTRAINT "FK_ac6032aa0438faf213f0419e029" FOREIGN KEY ("warehouseId") REFERENCES "${schema}"."warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."storage-bin" ADD CONSTRAINT "FK_bee13faf64529103e19077e6c75" FOREIGN KEY ("storageTypeId") REFERENCES "${schema}"."storage-type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."storage-bin" ADD CONSTRAINT "FK_37f500c4dd7f369e486852c91c2" FOREIGN KEY ("storageSectionId") REFERENCES "${schema}"."storage-section"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."storage-bin" ADD CONSTRAINT "FK_eb88cffe746762e0b284b8b481e" FOREIGN KEY ("activityAreaId") REFERENCES "${schema}"."activity-area"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."package-specification" ADD CONSTRAINT "FK_cdd031b6530cacbb4b324fc8217" FOREIGN KEY ("productId") REFERENCES "${schema}"."product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."package-specification" ADD CONSTRAINT "FK_9cb9f07effcface9ad147b203a3" FOREIGN KEY ("packgingMaterialId") REFERENCES "${schema}"."packging-material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."handling-unit" ADD CONSTRAINT "FK_841e9101c45a1c4600cc0d12f59" FOREIGN KEY ("productId") REFERENCES "${schema}"."product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."handling-unit" ADD CONSTRAINT "FK_03caab8a1fbd11970648c95bff5" FOREIGN KEY ("packageSpecificationId") REFERENCES "${schema}"."package-specification"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."handling-unit" ADD CONSTRAINT "FK_cc2488ff29dd1e3bea18d7b80dd" FOREIGN KEY ("packgingMaterialId") REFERENCES "${schema}"."packging-material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sourcing-shipment" ADD CONSTRAINT "FK_514276e6521690fd002e1953246" FOREIGN KEY ("sourcingOrderId") REFERENCES "${schema}"."sourcing-order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."account-payable" ADD CONSTRAINT "FK_22b94f1172a13fda9171f373dc8" FOREIGN KEY ("sourcingPaymentId") REFERENCES "${schema}"."sourcing-payment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."account" ADD CONSTRAINT "FK_1e29b83318370366d9791cedd89" FOREIGN KEY ("paymentVoucherId") REFERENCES "${schema}"."payment-voucher"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."payment-voucher" ADD CONSTRAINT "FK_15578b2e304515fe1d54872c03e" FOREIGN KEY ("sourcingPaymentId") REFERENCES "${schema}"."sourcing-payment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sourcing-payment" ADD CONSTRAINT "FK_6c179f84a8db0d9fbae03da8ea9" FOREIGN KEY ("sourcingOrderId") REFERENCES "${schema}"."sourcing-order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sourcing-order" ADD CONSTRAINT "FK_199c2265b6f7880f9f500b4e62c" FOREIGN KEY ("sourcingBusinessContractId") REFERENCES "${schema}"."sourcing-business-contract"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-sourcing-order" ADD CONSTRAINT "FK_8019c48a3507102dee498b916f6" FOREIGN KEY ("skuId") REFERENCES "${schema}"."sku"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-sourcing-order" ADD CONSTRAINT "FK_252b1efb7503c6911aaf45bbd92" FOREIGN KEY ("sourcingOrderId") REFERENCES "${schema}"."sourcing-order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-selling-contract" ADD CONSTRAINT "FK_c530bf8342d84f686c810283e51" FOREIGN KEY ("skuId") REFERENCES "${schema}"."sku"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-selling-contract" ADD CONSTRAINT "FK_407b8cfc3ece9c03d6e281671b6" FOREIGN KEY ("sellingBusinessContractId") REFERENCES "${schema}"."selling-business-contract"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."commission" ADD CONSTRAINT "FK_c452e76c3467cfb6c23fbe5d9fc" FOREIGN KEY ("sellingBusinessContractId") REFERENCES "${schema}"."selling-business-contract"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."selling-business-contract" ADD CONSTRAINT "FK_a472b4b28aef8e0c3cd79760e6c" FOREIGN KEY ("businessPartnerId") REFERENCES "${schema}"."business-partner"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."selling-shipment" ADD CONSTRAINT "FK_3ac515f6c9b4db426141ae72068" FOREIGN KEY ("sellingOrderId") REFERENCES "${schema}"."selling-order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."account-receivable" ADD CONSTRAINT "FK_e1f74a17ff57f3694a610b8a05f" FOREIGN KEY ("sellingPaymentId") REFERENCES "${schema}"."selling-payment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."revenue" ADD CONSTRAINT "FK_16c87a5a2c84b7e7442a42312f1" FOREIGN KEY ("receiptId") REFERENCES "${schema}"."receipt"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."receipt" ADD CONSTRAINT "FK_3c09edc09ba2bc0e997baa8d0cd" FOREIGN KEY ("sellingPaymentId") REFERENCES "${schema}"."selling-payment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."selling-payment" ADD CONSTRAINT "FK_c1857527941d478062650ceb3b0" FOREIGN KEY ("sellingOrderId") REFERENCES "${schema}"."selling-order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."selling-order" ADD CONSTRAINT "FK_2fbb814cb87057c7286e157f97e" FOREIGN KEY ("sellingBusinessContractId") REFERENCES "${schema}"."selling-business-contract"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-selling-order" ADD CONSTRAINT "FK_b4b99acb2785ef540eec9ee0cfe" FOREIGN KEY ("skuId") REFERENCES "${schema}"."sku"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-selling-order" ADD CONSTRAINT "FK_7c019e16b87fca07a15d2aeb457" FOREIGN KEY ("sellingOrderId") REFERENCES "${schema}"."selling-order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sku" ADD CONSTRAINT "FK_3e26cddeb944a9f397257bc89b5" FOREIGN KEY ("storageBinId") REFERENCES "${schema}"."storage-bin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sku" ADD CONSTRAINT "FK_0404dad5535025215ca6dbc024d" FOREIGN KEY ("handlingUnitId") REFERENCES "${schema}"."handling-unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sku" ADD CONSTRAINT "FK_f7c5daa51bd2d6ed2a6fae8d77b" FOREIGN KEY ("productId") REFERENCES "${schema}"."product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-sourcing-contract" ADD CONSTRAINT "FK_f83562fbcc31245c0618b7bc868" FOREIGN KEY ("skuId") REFERENCES "${schema}"."sku"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-sourcing-contract" ADD CONSTRAINT "FK_842f998bbfe173e487aab4b7ec4" FOREIGN KEY ("sourcingBusinessContractId") REFERENCES "${schema}"."sourcing-business-contract"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sourcing-business-contract" ADD CONSTRAINT "FK_53cff073aa38b2cc647cedcc565" FOREIGN KEY ("businessPartnerId") REFERENCES "${schema}"."business-partner"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const {schema} = queryRunner.connection.options as PostgresConnectionOptions;
        await queryRunner.query(`ALTER TABLE "${schema}"."sourcing-business-contract" DROP CONSTRAINT "FK_53cff073aa38b2cc647cedcc565"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-sourcing-contract" DROP CONSTRAINT "FK_842f998bbfe173e487aab4b7ec4"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-sourcing-contract" DROP CONSTRAINT "FK_f83562fbcc31245c0618b7bc868"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sku" DROP CONSTRAINT "FK_f7c5daa51bd2d6ed2a6fae8d77b"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sku" DROP CONSTRAINT "FK_0404dad5535025215ca6dbc024d"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sku" DROP CONSTRAINT "FK_3e26cddeb944a9f397257bc89b5"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-selling-order" DROP CONSTRAINT "FK_7c019e16b87fca07a15d2aeb457"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-selling-order" DROP CONSTRAINT "FK_b4b99acb2785ef540eec9ee0cfe"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."selling-order" DROP CONSTRAINT "FK_2fbb814cb87057c7286e157f97e"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."selling-payment" DROP CONSTRAINT "FK_c1857527941d478062650ceb3b0"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."receipt" DROP CONSTRAINT "FK_3c09edc09ba2bc0e997baa8d0cd"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."revenue" DROP CONSTRAINT "FK_16c87a5a2c84b7e7442a42312f1"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."account-receivable" DROP CONSTRAINT "FK_e1f74a17ff57f3694a610b8a05f"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."selling-shipment" DROP CONSTRAINT "FK_3ac515f6c9b4db426141ae72068"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."selling-business-contract" DROP CONSTRAINT "FK_a472b4b28aef8e0c3cd79760e6c"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."commission" DROP CONSTRAINT "FK_c452e76c3467cfb6c23fbe5d9fc"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-selling-contract" DROP CONSTRAINT "FK_407b8cfc3ece9c03d6e281671b6"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-selling-contract" DROP CONSTRAINT "FK_c530bf8342d84f686c810283e51"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-sourcing-order" DROP CONSTRAINT "FK_252b1efb7503c6911aaf45bbd92"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."product-sourcing-order" DROP CONSTRAINT "FK_8019c48a3507102dee498b916f6"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sourcing-order" DROP CONSTRAINT "FK_199c2265b6f7880f9f500b4e62c"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sourcing-payment" DROP CONSTRAINT "FK_6c179f84a8db0d9fbae03da8ea9"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."payment-voucher" DROP CONSTRAINT "FK_15578b2e304515fe1d54872c03e"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."account" DROP CONSTRAINT "FK_1e29b83318370366d9791cedd89"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."account-payable" DROP CONSTRAINT "FK_22b94f1172a13fda9171f373dc8"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."sourcing-shipment" DROP CONSTRAINT "FK_514276e6521690fd002e1953246"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."handling-unit" DROP CONSTRAINT "FK_cc2488ff29dd1e3bea18d7b80dd"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."handling-unit" DROP CONSTRAINT "FK_03caab8a1fbd11970648c95bff5"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."handling-unit" DROP CONSTRAINT "FK_841e9101c45a1c4600cc0d12f59"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."package-specification" DROP CONSTRAINT "FK_9cb9f07effcface9ad147b203a3"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."package-specification" DROP CONSTRAINT "FK_cdd031b6530cacbb4b324fc8217"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."storage-bin" DROP CONSTRAINT "FK_eb88cffe746762e0b284b8b481e"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."storage-bin" DROP CONSTRAINT "FK_37f500c4dd7f369e486852c91c2"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."storage-bin" DROP CONSTRAINT "FK_bee13faf64529103e19077e6c75"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."storage-type" DROP CONSTRAINT "FK_ac6032aa0438faf213f0419e029"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."storage-section" DROP CONSTRAINT "FK_398a26bd1bdcc7b90304232cfac"`);
        await queryRunner.query(`ALTER TABLE "${schema}"."activity-area" DROP CONSTRAINT "FK_d8d7d51e82a7eb6b08f5d110e23"`);
        await queryRunner.query(`DROP TABLE "${schema}"."business-partner"`);
        await queryRunner.query(`DROP TABLE "${schema}"."sourcing-business-contract"`);
        await queryRunner.query(`DROP TABLE "${schema}"."product-sourcing-contract"`);
        await queryRunner.query(`DROP TABLE "${schema}"."sku"`);
        await queryRunner.query(`DROP TABLE "${schema}"."product-selling-order"`);
        await queryRunner.query(`DROP TABLE "${schema}"."selling-order"`);
        await queryRunner.query(`DROP TABLE "${schema}"."selling-payment"`);
        await queryRunner.query(`DROP TABLE "${schema}"."receipt"`);
        await queryRunner.query(`DROP TABLE "${schema}"."revenue"`);
        await queryRunner.query(`DROP TABLE "${schema}"."account-receivable"`);
        await queryRunner.query(`DROP TABLE "${schema}"."selling-shipment"`);
        await queryRunner.query(`DROP TABLE "${schema}"."selling-business-contract"`);
        await queryRunner.query(`DROP TABLE "${schema}"."commission"`);
        await queryRunner.query(`DROP TABLE "${schema}"."product-selling-contract"`);
        await queryRunner.query(`DROP TABLE "${schema}"."product-sourcing-order"`);
        await queryRunner.query(`DROP TABLE "${schema}"."sourcing-order"`);
        await queryRunner.query(`DROP TABLE "${schema}"."sourcing-payment"`);
        await queryRunner.query(`DROP TABLE "${schema}"."payment-voucher"`);
        await queryRunner.query(`DROP TABLE "${schema}"."account"`);
        await queryRunner.query(`DROP TABLE "${schema}"."account-payable"`);
        await queryRunner.query(`DROP TABLE "${schema}"."sourcing-shipment"`);
        await queryRunner.query(`DROP TABLE "${schema}"."handling-unit"`);
        await queryRunner.query(`DROP TABLE "${schema}"."product"`);
        await queryRunner.query(`DROP TABLE "${schema}"."package-specification"`);
        await queryRunner.query(`DROP TABLE "${schema}"."packging-material"`);
        await queryRunner.query(`DROP TABLE "${schema}"."storage-bin"`);
        await queryRunner.query(`DROP TABLE "${schema}"."storage-type"`);
        await queryRunner.query(`DROP TABLE "${schema}"."storage-section"`);
        await queryRunner.query(`DROP TABLE "${schema}"."warehouse"`);
        await queryRunner.query(`DROP TABLE "${schema}"."activity-area"`);
        await queryRunner.query(`DROP TABLE "${schema}"."tax-expense"`);
        await queryRunner.query(`DROP TABLE "${schema}"."selling-expense"`);
        await queryRunner.query(`DROP TABLE "${schema}"."da-expense"`);
        await queryRunner.query(`DROP TABLE "${schema}"."adm-expense"`);
    }

}
